# Generated by Django 3.1.5 on 2021-04-10 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estato_lampada', models.BooleanField(default=False)),
                ('ligou_iot_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temporizadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.IntegerField()),
                ('estato', models.BooleanField(default=True)),
                ('coias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IoT.coisa')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=20)),
                ('tempo_ligado', models.PositiveBigIntegerField()),
                ('preço', models.FloatField()),
                ('coias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IoT.coisa')),
            ],
        ),
    ]
