# Generated by Django 3.1.5 on 2021-04-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0002_auto_20210410_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporizadores',
            name='horario',
            field=models.IntegerField(),
        ),
    ]
