# Generated by Django 3.1.5 on 2021-04-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0003_auto_20210410_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coisa',
            old_name='nome',
            new_name='slug',
        ),
    ]
