# Generated by Django 3.1.5 on 2021-04-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0004_auto_20210410_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporizadores',
            name='pos',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
