# Generated by Django 3.1.5 on 2021-04-11 19:50

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0005_temporizadores_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporizadores',
            name='pos',
            field=models.PositiveSmallIntegerField(default=builtins.id, unique=True),
        ),
    ]
