# Generated by Django 3.1.5 on 2021-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0007_auto_20210411_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporizadores',
            name='pos',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
