# Generated by Django 3.1.5 on 2021-04-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0008_auto_20210411_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporizadores',
            name='pos',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
