# Generated by Django 3.1.5 on 2021-04-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0009_auto_20210411_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporizadores',
            old_name='coias',
            new_name='coisa',
        ),
    ]
