# Generated by Django 3.1.5 on 2021-04-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0010_auto_20210411_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='coias',
            new_name='coisa',
        ),
    ]
