# Generated by Django 3.1.5 on 2021-04-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0011_auto_20210411_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='mes_ano',
        ),
        migrations.AddField(
            model_name='historico',
            name='date',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporizadores',
            name='estato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='temporizadores',
            name='horario',
            field=models.CharField(max_length=8),
        ),
    ]
