# Generated by Django 3.1.5 on 2021-04-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0013_auto_20210415_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coisa',
            name='ligou_iot_at',
        ),
        migrations.AddField(
            model_name='coisa',
            name='potencia',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
